artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://raw.githubusercontent.com/trandinhthang203/Machine-Learning-Projects/refs/heads/main/ML/insurance.csv
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion


data_validation:
  root_dir: artifacts/data_validation
  unzip_dir_data: artifacts/data_ingestion/data.csv
  STATUS_FILE: artifacts/data_validation/status.json
  validation_report_name: validation_report.json


data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/data.csv
  data_transform_path: artifacts/data_transformation/data.csv


model_trainer:
  root_dir: artifacts/model_trainer
  data_path: artifacts/data_transformation/data.csv
  train_path: artifacts/data_transformation/train.csv
  test_path: artifacts/data_transformation/test.csv
  model_name: model.joblib


model_evaluation:
  root_dir: artifacts/model_evaluation
  test_path: artifacts/data_transformation/test.csv
  model_path: artifacts/model_trainer/model.joblib
  metric_file_name: artifacts/model_evaluation/metrics.json